spring.application.name=gateway-service
server.port=8101
eureka.client.service-url.default-zone=http://localhost:8761/eureka

zuul.routes.order-service.path = /order-service/**
zuul.routes.order-service.serviceId = order-service
zuul.routes.order-service.url =  http://localhost:8103/

zuul.routes.product-service.path = /product-service/**
zuul.routes.product-service.serviceId = product-service
zuul.routes.product-service.url = http://localhost:8106/

zuul.routes.mail-service.path = /mail-service/**
zuul.routes.mail-service.serviceId = mail-service
zuul.routes.mail-service.url = http://localhost:8124/


zuul.routes.logs-service.path = /logs-service/**
zuul.routes.logs-service.serviceId = logs-service
zuul.routes.logs-service.url = http://localhost:8108/

management.endpoints.web.exposure.include=*
management.endpoint.routes.enabled=true
management.endpoint.filters.enabled=true

spring.datasource.url = jdbc:mariadb://localhost:3306/getwayapi
spring.datasource.username = root
spring.datasource.password = dinhnguyen
spring.datasource.driver-class-name = org.mariadb.jdbc.Driver
spring.jpa.show-sql = true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update